#!/bin/sh /etc/rc.common

#DEBUG=echo
START=39
STOP=91

MAC="$(uci_get wireless "radio0" macaddr)"

apply_wireless_defaults() {
  $DEBUG uci_set wireless @wifi-device[0] disabled 0
  $DEBUG uci_set wireless @wifi-iface[0] network mesh
  $DEBUG uci_set wireless @wifi-iface[0] mode adhoc
  $DEBUG uci_set wireless @wifi-iface[0] ssid commotion-mesh
  $DEBUG uci_add wireless wifi-iface
  $DEBUG uci_set wireless @wifi-iface[-1] device radio0
  $DEBUG uci_set wireless @wifi-iface[-1] network ap
  $DEBUG uci_set wireless @wifi-iface[-1] mode ap
  $DEBUG uci_set wireless @wifi-iface[-1] encryption none
  $DEBUG uci_set wireless @wifi-iface[-1] ssid commotion-ap_"$( echo $MAC | \
   awk -F ':' '{ printf("%d_%d_%d","0x"$4,"0x"$5,"0x"$6) }' )"
  $DEBUG uci_commit wireless && return 0
}

apply_hostname_defaults() {
  
  local hostname="$(uci_get mesh network basename "commotion")_$(uci_get mesh node location $( echo $MAC | \
   awk -F ':' '{ printf("%d_%d_%d","0x"$4,"0x"$5,"0x"$6) }' ))"

  echo "$hostname" > /proc/sys/kernel/hostname
  $DEBUG uci_set system system hostname "$hostname"
  $DEBUG uci_commit system && return 0
}


boot() {
  grep -qs config /etc/config/wireless || { 
    rm -f /etc/config/wireless
    $DEBUG /sbin/wifi detect > /etc/config/wireless
    $DEBUG apply_wireless_defaults
  }
  
  apply_hostname_defaults
}
   
