#!/bin/sh

[ -f "/usr/share/commotion/files/node-mini.gif" ] && { \
cp -f /use/share/commotion/files/node-mini.gif /www/luci-ststic/resources/olsr-viz/node-mini.gif
}

[ -f "/usr/share/commotion/files/node-hna-mini.gif" ] && { \
cp -f /use/share/commotion/files/node-hna-mini.gif /www/luci-ststic/resources/olsr-viz/node-hna-mini.gif
}

[ -f "/usr/share/commotion/files/olsr-viz.sh" ] && { \
cp -f /use/share/commotion/files/olsr-viz.sh /www/cgi-bin/olsr-viz.sh
}

[ -f "/usr/bin/patch" ] && { \
  cd /usr/lib/lua/luci/
  patch -p0 < /usr/share/commotion/patches/luci_splash.patch

  cd /
  patch -p3 < /usr/share/commotion/patches/luci-splash_fix-dropped-clients.diff
}
  


uci -q batch <<-EOF >/dev/null
	delete ucitrack.@mesh[-1]
	add ucitrack mesh
	set ucitrack.@mesh[-1].init=meshconfig
	add_list ucitrack.@mesh[-1].affects=network
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache

cat > /usr/lib/luci-splash/splashtext.html <<EOF
<h2> <a id="content" name="content">Welcome!</a> </h2>
<p>
You are now connected to a <a href="http://commotionwireless.net">Commotion</a> community wireless network.
</p>

<p>
<strong>Access to the Internet</strong> may be provided by people donating connectivity to the network. Everyone on the network has to share, so please be aware and behave yourself
 accordingly:
<ul>
<li>Please <strong>avoid large downloads and excessive filesharing.</strong></li>
<li>Please <strong>no illegal activities.</strong></li>
</ul>
</p>

If you like the network, please consider contributing!

<p>
By clicking on <em>###ACCEPT###</em>, you gain access to the network for ###LEASETIME### hour(s). Then you will be directed to this splash page again.
</p>
EOF
exit 0
