#!/bin/sh

[ -f "/usr/bin/patch" ] && { \
  cd /usr/lib/lua/luci/model/cbi/admin_network/
  patch < /usr/share/commotion/patches/luci-admin.patch
  
  cd /etc/init.d/
  patch < /usr/share/commotion/patches/dnsmasq.patch
}

if ! grep -q "meshconfig" /etc/crontabs/root 2>/dev/null; then
	echo "0 */1 * * *	/etc/init.d/meshconfig cron" >> /etc/crontabs/root
fi

exit 0
