#!/bin/sh

[ -f "/usr/bin/patch" ] && { \
  cd /etc/init.d/
  patch -p0 < /usr/share/commotion/patches/dnsmasq.patch
  patch -p0 < /usr/share/commotion/patches/n2n.patch
  
  cd /usr/sbin/
  patch -p0 < /usr/share/commotion/patches/remote-update.patch
}

[ -f "/usr/share/commotion/files/banner" ] && { \
  cp -f /usr/share/commotion/files/banner /etc/banner
}

if ! grep -q "meshconfig" /etc/crontabs/root 2>/dev/null; then
	echo "0 */1 * * *	/etc/init.d/meshconfig cron" >> /etc/crontabs/root
fi

exit 0
