#!/bin/sh

. /etc/functions.sh
. /lib/functions/commotion.sh

[ ! -f /etc/config/wireless ] && wifi detect > /etc/config/wireless

commotion_set_nodeid_from_mac $(uci get wireless.@wifi-device[0].macaddr)
uci_set commotiond @node[0] id $(commotion_get_nodeid)
uci_commit commotiond

if [ -f /etc/commotion/profiles.d/RHIAP -a -f /etc/commotion/profiles.d/RHIMesh ]; then

uci_set wireless @wifi-device[0] disabled 0
uci_set wireless @wifi-device[0] channel 5
uci_remove wireless @wifi-iface[0]
uci_add wireless wifi-iface RHIMesh
uci_set wireless RHIMesh device radio0
uci_set wireless RHIMesh mode adhoc
uci_set wireless RHIMesh network mesh
uci_set wireless RHIMesh ssid "commotionwireless.net"
uci_add wireless wifi-iface RHIAP
uci_set wireless RHIAP device radio0
uci_set wireless RHIAP mode ap
uci_set wireless RHIAP network ap
uci_set wireless RHIAP ssid RHIwifi
uci_commit wireless

/etc/init.d/commotion restart
/etc/init.d/network restart

fi

exit 0
